#默认使用配置
spring:
  profiles:
    active: dev
  datasource:
    name: caifeng
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.9.155.149:3306/caifeng?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: caifeng
    password: pNrApiSx5Ti2iPNF
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri:  mongodb://caifeng:caifEng666@139.9.155.149:27017/?authSource=caifeng
      database: caifeng
  #SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB
cf:
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: UTF-8
    tracker_servers: 139.9.155.149:22122 #多个 trackerServer中间以逗号分隔
#  redis:
#    host: 139.9.155.149
#    port: 6379
#    pass:
#    database: 0
#    maxIdle: 300
#    maxWait: 3000
#    testOnBorrow: true

#公共配置与profiles选择无关
mybatis:
  #  mapperScanPackage: com.cf.mapper
  #  typeAliasesPackage: com.cf.pojo
  mapperLocations: classpath:com.cf.chat.dao.mapper/*.xml
  configLocation: classpath:config/SqlMapConfig.xml
